import { CertificateRecord } from '../types/certificate';

export const SAMPLE_CERTIFICATES: CertificateRecord[] = [
  {
    id: 'cert-001',
    projectName: 'โครงการวันภาษาไทยแห่งชาติ ประจำปี ๒๕๖๗',
    studentId: '640610123',
    name: 'นายกิตติศักดิ์ รัตนวิเชียร',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๑/๒๕๖๗',
    role: 'รางวัลชนะเลิศ การประกวดแต่งคำประพันธ์ร้อยกรอง',
    issueDate: '๒๙ กรกฎาคม ๒๕๖๗',
  },
  {
    id: 'cert-002',
    projectName: 'โครงการวันภาษาไทยแห่งชาติ ประจำปี ๒๕๖๗',
    studentId: '640610124',
    name: 'นางสาวชนกนันท์ สิริวรพงศ์',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๒/๒๕๖๗',
    role: 'รางวัลรองชนะเลิศอันดับ ๑ การแข่งขันทักษะการอ่านทำนองเสนาะ',
    issueDate: '๒๙ กรกฎาคม ๒๕๖๗',
  },
  {
    id: 'cert-003',
    projectName: 'โครงการสัมมนาวิชาการและการจัดการเรียนรู้ภาษาไทยศตวรรษที่ ๒๑',
    studentId: '650610235',
    name: 'นายวรเมธ ประเสริฐสุข',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๓/๒๕๖๗',
    role: 'ผ่านการอบรมเชิงปฏิบัติการ จำนวน ๑๒ ชั่วโมง',
    issueDate: '๑๕ สิงหาคม ๒๕๖๗',
  },
  {
    id: 'cert-004',
    projectName: 'โครงการสัมมนาวิชาการและการจัดการเรียนรู้ภาษาไทยศตวรรษที่ ๒๑',
    studentId: '650610236',
    name: 'นางสาวกานดา นวลจันทร์',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๔/๒๕๖๗',
    role: 'ผ่านการอบรมเชิงปฏิบัติการ จำนวน ๑๒ ชั่วโมง',
    issueDate: '๑๕ สิงหาคม ๒๕๖๗',
  },
  {
    id: 'cert-005',
    projectName: 'โครงการค่ายเสริมสร้างจิตวิญญาณความเป็นครูภาษาไทย ครั้งที่ ๑๕',
    studentId: '660610340',
    name: 'นายภานุวัฒน์ วงศ์สุวรรณ',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๕/๒๕๖๗',
    role: 'ผู้เข้าร่วมกิจกรรมค่ายเสริมสร้างจิตวิญญาณความเป็นครูภาษาไทย',
    issueDate: '๑๐ ตุลาคม ๒๕๖๗',
  },
  {
    id: 'cert-006',
    projectName: 'โครงการค่ายเสริมสร้างจิตวิญญาณความเป็นครูภาษาไทย ครั้งที่ ๑๕',
    studentId: '660610341',
    name: 'นางสาวพิมลพรรณ สุริยะ',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๖/๒๕๖๗',
    role: 'คณะกรรมการดำเนินงานฝ่ายวิชาการและพิธีการ',
    issueDate: '๑๐ ตุลาคม ๒๕๖๗',
  },
  {
    id: 'cert-007',
    projectName: 'การแข่งขันทักษะการเปิดพจนานุกรมและรอบรู้ภาษาไทย',
    studentId: '660610342',
    name: 'นายธนพล สุขสมบูรณ์',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๗/๒๕๖๗',
    role: 'รางวัลชนะเลิศ การแข่งขันรอบรู้ภาษาไทย',
    issueDate: '๒๙ กรกฎาคม ๒๕๖๗',
  },
  {
    id: 'cert-008',
    projectName: 'การแข่งขันทักษะการเปิดพจนานุกรมและรอบรู้ภาษาไทย',
    studentId: '640610125',
    name: 'นางสาวมณีรัตน์ วงศ์วิวัฒน์',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    certificateNo: 'ศศ.ภท. ๐๘/๒๕๖๗',
    role: 'รางวัลรองชนะเลิศ การแข่งขันรอบรู้ภาษาไทย',
    issueDate: '๒๙ กรกฎาคม ๒๕๖๗',
  }
];
